version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: dockerhub.sliton.ru/gitea/gitea:1.16.4
    container_name: gittut
    env_file:
      - ./.env
    restart: always
    networks:
      - gitea
    volumes:
      - /storage0/docker_mounts/gittut:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
    depends_on:
       - db
    networks:
      - gittut
  db:
    image: dockerhub.sliton.ru/postgres:13.6
    container_name: gittut_db
    restart: always
    env_file:
      - ./.env
    volumes:
      - /opt/docker/gittut/postgres:/var/lib/postgresql/data
    networks:
      - gittut
networks:
  gittut:
    driver: bridge