version: "3"

networks:
  gitea:
    external: false

services:
  pgadmin:
    container_name: gittut-pgadmin4
    image: dpage/pgadmin4:6.14
    restart: always
    ports:
      - "5051:80"
    env_file:
      - ./stack.env
    networks:
      - gittut
  server:
    image: gitea/gitea:1.17.2
    container_name: gittut
    env_file:
      - ./stack.env
    restart: always
    networks:
      - gitea
    volumes:
      - gittut-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:3000"
    depends_on:
       - db
    networks:
      - gittut
  db:
    image: postgres:14
    container_name: gittut_db
    restart: always
    env_file:
      - ./stack.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - gittut
networks:
  gittut:
    driver: bridge

volumes:
  postgresql-data:
    driver: local
  repos:
    driver: local
